### ISSUE TITLE
Bug in config option PostMaster::PreFilterModule###1-SystemMonitoring

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/SystemMonitoring#1]
Dear OTOBO Team,

I think we have a small bug in SystemMonitoring config option:

PostMaster::PreFilterModule###1-SystemMonitoring

There are two config options in this area:

PostMaster::PreFilterModule###00-SystemMonitoring
and
PostMaster::PreFilterModule###1-SystemMonitoring

The second option should read "PostMaster::**Post**FilterModule###**0**1-SystemMonitoring"
The description show, that the option is a post module. So we need to check the code, if "Post" already exist, or if only "Pre" now exist. Than we need to change the description.
And we need to disable this option by default. It makes no sense that the first option is disabled and the second is active. Both should disabled by default.

Thanks!

Stefan

**Comment by stefanhaerter** [comment]
When changing this, keep in mind that on existing systems which have a modified setting, this would be deleted. Probably its effective value could be copied to the PreFilterModule###00, but only if this is disabled.

**Comment by stefanhaerter** [comment]
Decision was to leave things as they are and just change the description. Commit pushed, closing the issue.
